#SPDX-License-Identifier: MIT-0
---
# tasks file for acr_conf

- name: Iniciar sesión en ACR
  containers.podman.podman_login:
    registry: "{{ acr_login_server }}"
    username: "{{ acr_admin_username }}"
    password: "{{ acr_admin_password }}"

- name: Descargar imagen de nginx
  include_tasks: Pullnginx.yml


- name: Cerrar sesión de ACR
  containers.podman.podman_logout:
    registry: "{{ acr_login_server }}"