- name: Descargar imagen de redis
  containers.podman.podman_image:
    name: "docker.io/jsosa15/azure-vote-front"
    tag: v1
    pull: true

- name: Etiquetar la imagen para ACR
  containers.podman.podman_tag:
    image: "docker.io/jsosa15/azure-vote-front:v1"
    target_names:
      - "{{ acr_login_server }}/azure-vote-front:cp2"

- name: Subir imagen a ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/azure-vote-front"
    tag: cp2
    push: true
