- name: Descargar imagen de redis
  containers.podman.podman_image:
    name: "docker.io/jsosa15/redis:6.0.8"
    tag: 6.0.8
    pull: true

- name: Etiquetar la imagen para ACR
  containers.podman.podman_tag:
    image: "docker.io/jsosa15/redis:6.0.8"
    target_names:
      - "{{ acr_login_server }}/redis:cp2"

- name: Subir imagen a ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/redis"
    tag: cp2
    push: true
