---
# tasks file for AKS_conf

- name: Creación del namespace
  ansible.builtin.include_tasks: CreateNamespace.yml

- name: Creación del PersistentVolumeClaim
  ansible.builtin.include_tasks: CreatePVC.yml

- name: Creación del Redis
  ansible.builtin.include_tasks: ConfRedis.yml

- name: Desplegar Frontend (Azure Vote)
  ansible.builtin.include_tasks: ConfVote.yml
