---
- name: Creación del namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    template: namespace.j2

- name: Creación del PersistentVolumeClaim
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    template: pvc.j2

- name: Desplegar Redis
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    template: backend.j2

- name: Desplegar Frontend
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    template: frontend.j2
