- name: Descargar imagen de nginx
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/nginx"
    tag: cp2
    pull: true

- name: Crear directorio para datos de nginx
  ansible.builtin.file:
    path: "{{ path_data }}"
    state: directory
    mode: '0755'

- name: Crear index.html
  ansible.builtin.copy:
    src: "index.html"
    dest: "{{ path_data }}/index.html"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Generar archivo de autenticación (.htpasswd)
  community.general.htpasswd:
    path: "{{ path_data }}/.htpasswd"
    name: "{{ nginx_user }}"
    password: "{{ nginx_pass }}"
    owner: root
    group: root
    mode: '0644'

- name: Crear configuración Nginx con Auth activada
  ansible.builtin.copy:
    src: "default.conf"
    dest: "{{ path_data }}/default.conf"
