- name: Cifrar secretos generados por Terraform
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cifrar secrets.yml
      ansible.builtin.command:
        cmd: "ansible-vault encrypt secrets.yml --vault-password-file ~/.vault_pass"
      ignore_errors: true

- name: Subir imágenes a ACR
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  roles:
    - acr_conf

- name: Configurar vm y arrancar contenedor
  hosts: vm
  gather_facts: false
  become: true
  vars_files:
    - secrets.yml
  roles:
    - vm_container

- name: Arrancar app en AKS
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  roles:
    - aks_deploy
